### ISSUE TITLE
Unable to generate binary

### ISSUE THREAD

**Issue by Bot101-101** [Serphyus/Centox#3]
My terminal 

Centox] $ generate -o /home/user/inject.bin -l no
*] created temporary folder -> /tmp/tmp_jrucd6s
[*] converting payload to format: ducky
[*] writing raw payload to -> /tmp/tmp_jrucd6s/payload
[*] compiling payload to injection binary...
[-] unable to generate inject.bin

Does someone how's, why it cannot generate ?

**Comment by shi88ihs** [comment]
Which USB Device are you working with? Since this project makes binaries and not clear text. I don't find it very useful since I can't read what it its generating. It's probably only used for the Microcontrollers like the Phison MC on USB Devices that work at the USB microcontroller level. It's better to use Rucky an Android app or a flipper zero for USB scripts. I usually just the scripting ability for entering complex passwords or automating other useful tasks. So use the auto typing feature of Rucky or Flipper Zero for simple and good useful tasks first. The reverse shells in binary form is complex stuff and probably means you need a good understanding of which USB controller can run a binary file in the first place. Be a responsible and good person with your cyber security research. We need more white hat gurus to help out with our nations companies and militaries. Join my tele-G blog/chat:  t dot me slash +8IEWhlQ8DRRkMTU1

**Comment by shi88ihs** [comment]
This is bad English too. The title should be: 'Unable to Successfully Generate a Binary'. Just make regular Ducky Scripts for useful automation. Avoid making binary files that are unreadable. I think editing the source code of this project so it makes readable Ducky Scripts would be a useful undertaking.

**Comment by Serphyus** [comment]
I have been working on changes to the project recently due to Hak5's PayloadStudio. I had planned for this project to function as a payload generator rather than a compiler. These changes are in the process of being developed and will soon be released. When released the scripts generated by Centox can be compiled using the Hak5 PayloadStudio to support all devices compatible with ducky script.

**Comment by Serphyus** [comment]
Issue should now be fixed and Centox will no longer compile to binary but rather generate a ducky script. Devices that require compiling to binary will have to use Hak5's official compiler in their [PayloadStudio](https://payloadstudio.hak5.org) after generating the payload.
